project:
  type: website
  output-dir: docs

website:
  title: "Alexandria Reed"
  favicon: image/logo1.png
  navbar:
    logo: image/logo1.png
    right: 
      - icon: github
        href: https://github.com/reedalexandria
      - icon: twitter
        href: https://twitter.com/reedalexandria1
      - icon: linkedin
        href: https://www.linkedin.com/in/alexandria-reed-579132128/
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd #resume/resume.pdf
        text: Resume
      - href: blog_posts.qmd
        text: Blog Posts
  page-footer: 
    background: "#124559"
    left: "Copyright 2022, Alexandria Reed"
    right: 
      - icon: github
        text: Source Code 
        href: https://github.com/reedalexandria/reedalexandria.github.io

  plugins:
  - quarto-clipboard
        
format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    mainfont: Montserrat
    toc: true

editor: visual

