project:
  type: website
  output-dir: docs

website:
  title: "Alexandria Reed"
  favicon: images/AR_logo.png
  navbar:
    logo: image/AR_logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume/resume.pdf
        text: Resume
      - href: blog_posts.qmd
        text: Blog Posts
  page-footer: 
    background: "#124559"
    left: "Copyright 2022, Alexandria Reed"
    right: 
      - icon: github
        href: https://github.com/reedalexandria
      - icon: twitter
        href: https://twitter.com/reedalexandria1
        
format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    mainfont: Montserrat
    toc: true

editor: visual

