project:
  type: website
  output-dir: docs

website:
  title: "reedalexandria.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - href: blog_posts.qmd
        text: Blog post
format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    mainfont: Montserrat
    toc: true

editor: visual

