project:
  type: website
  output-dir: docs

website:
  title: "reedalexandria.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume/resume.pdf
        text: Resume
      - href: blog_posts.qmd
        text: Blog Posts
format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    mainfont: Montserrat
    toc: true

editor: visual

