project:
  type: website
  output-dir: docs

website:
  title: "Alexandria Reed"
  navbar:
    title: false
    logo: image/AR-1.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume/resume.pdf
        text: Resume
      - href: blog_posts.qmd
        text: Blog Posts
    collapse-below: sm
    search: true
  page-footer: 
    background: "#124559"
    left: "Copyright 2022, Alexandria Reed"
    right: 
      - icon: github
        href: https://github.com/reedalexandria
      - icon: twitter
        href: https://twitter.com/reedalexandria1
        
format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    mainfont: Montserrat
    toc: true

editor: visual

