---
title: "About"
---

<h3 class ="custom-subtitle">

About Me </h3>

I'm a graduate student in the Master of Environmental Data Science program at the Bren School of Environmental Science & Management at UC Santa Barbara. My current interests lie in sustainable food systems, addressing climate change, and reducing carbon footprints. I completed my undergraduate studies at UC Santa Barbara in 2017, graduating with a Bachelor of Science in Environmental Studies. As an undergraduate student, I led reforestation and sustainable agriculture projects in South America for a nonprofit organization. After graduating, I worked as an Environmental Specialist for an Environmental, Health, Safety, and Sustainability consulting company, where I evaluated and identified environmental impacts as well as recommended and implemented solutions for clients in the private and public sectors. During my time working as an environmental consultant, I observed the disproportionate environmental impacts in marginalized communities and the need for reproducible data science and visualization skills to develop solutions to environmental issues. My goal is to utilize data science tools to derive data-driven solutions for complex environmental problems and effectively communicate the information so that it is accessible and enacts change.

<h3 class ="custom-subtitle">

Education </h3>

\*\*Master of Environmental Data Science\*\*, (Expected June 2023) \\\| Bren School of Environmental Science & Management University of California, Santa Barbara (UCSB)

\*\*Bachelor of Science in Environmental Studies\*\*, (June 2017)\\\| UCSB, Santa Barbara, CA

<h3 class ="custom-subtitle">

Experience </h3>

\*\*Environmental Specialist\*\* (2018-present) \\\| Citadel EHS, Glendale, CA

<h1>

this is my h1 element</h>

<h1 class="title">

this is a black h1 element

</h1>
