---
title: "Resume"
---

[Download Resume](resume.pdf){style="color: #124559"}

::: panel-tabset
### Summary of Qualifications

-   Data-driven environmental specialist with a Master of Environmental Data Science (expected June 2023) and a Bachelor of Science in Environmental Studies.
-   Extensive experience in the environmental sector, including roles with non-profit organizations, public research universities, and consulting companies.
-   Experienced in collaborating with diverse teams on data-driven research projects to develop innovative solutions to complex environmental challenges.
-   Skilled in programming languages such as R and Python, with digital literacy skills in GitHub, Git, Excel, PowerPoint, and QGIS.

### Education

**Master of Environmental Data Science (June 2023) \| Bren School of Environmental Science & Management -- University of California, Santa Barbara (UCSB)**

> **Highlighted Coursework:** Statistics for Environmental Data Science, Geospatial and Remote Sensing, Data Visualization and Communication, Machine Learning, Modeling Environmental Systems, Databases and Data Management

> **Leadership/Involvement:** Class Chair, Dean's Advisory Council

**Bachelor of Science in Environmental Studies (June 2017) \| University of California, Santa Barbara (UCSB)**

> **Highlighted Coursework:** Probability and Statistics, Solar and Renewable Energy Systems, Energy and the Environment, Principle Environmental Planning, Diet and Climate Change

### Data Science Projects

**Data Science Master's Capstone Project (1/23--Present) \|Informing Forest Conservation Regulations in Paraguay \| Clients: Dr. Robert Heilmayr, UCSB; Paraguay's National Forestry Institute (INFONA)**

> -   Produced and shared publicly facing materials on the project as required by the Bren School and/or client; organized and communicated team meetings; and managed GitHub projects and weekly tasks.
>
>     </blockquote>

> -   Assessed land use plan compliance and deforestation rates in the Chaco using geospatial overlays in R, determining that 82% of properties exhibited land use compliance.

> -   Constructed a simulation tool in R to estimate protected forest area under current and alternate laws in the undeveloped Chaco region.

> -   Implemented a Random Forest machine learning model and Google Earth Engine workflow in Python for data acquisition and preprocessing, predicting future deforestation patterns and generating pixel-wise probabilities of future deforestation.

> -   Developed an interactive Shiny dashboard for stakeholders to visualize results, guiding informed decisions on forest conservation and land use policies.

**Statistics for Environmental Data Science Final Project (11/22--12/22)**

> -   Investigated the relationship between poverty rates and the probability of concentrated animal feeding operation (CAFO) presence in California.

> -   Used a generalized linear model (GLM) to analyze relevant data and found a statistically significant relationship between poverty rates and the presence of CAFOs in California.

> -   Results provided evidence that CAFO pollution disproportionately affects people with high poverty rates in California, raising environmental justice issues.

**Dust Emission Monitoring (1/20--8/22) Environmental Compliance Consulting \| Role: Project Manager \| Client: KPRS Construction Services Inc.**

> - Oversaw the installation and maintenance of field monitoring equipment and managed daily operations relating to dust monitoring in lead-impacted soil during the redevelopment of a former cement plant.

> - Compiled, wrangled, analyzed, and prepared reports of wind and dust data for weekly submissions to regulatory bodies, including the South Coast Air Quality Management District (SCAQMD) and the Department of Toxic Substances Control (DTSC).

> - Mitigated compliance issues and reduced particulate emissions to safeguard community health.

### Professional Experience

**Citadel EHS, Glendale, CA Environmental Specialist (1/18--8/22 Full Time; 8/22--Present Part-Time)**

> - Created visualizations including figures and maps to enhance data representation and communicate findings.

> - Oversee wastewater surveillance projects for the presence of SARS-COV-2. Successfully identify the presence of COVID in wastewater and implement measures to reduce the risk of outbreaks.

> - Prepare Phase I Environmental Site Assessments and conduct Phase II Site Investigations, consisting of soil, soil vapor, groundwater, and indoor air sample collection.

> - Manage radon surveying projects for various multi-family residential clients.

> - Conduct hazardous material inventories, environmental audits, and facility inspections.

**UCSB, Santa Barbara, CA Course Reader (10/22-12/22 Part-Time)**

> -   Graded essays and assignments submitted by undergraduate students enrolled in ENV S 193ST Sea Turtle Conservation & Management course.

> -   Posted grades and provided constructive feedback on the online learning management system in a timely and accurate manner to help students improve their writing and critical thinking skills.

**Cheadle Center for Biodiversity and Ecological Restoration (CCBER), Santa Barbara, CA Environmental Educator (4/17--6/17) \| Restoration Intern (3/16--6/16)**

> -   Led weekly fieldtrips, workshops, and created unique lesson plans to increase knowledge about environmental sciences for fifth graders.

> -   Monitored vegetation and wildlife, managed invasive species, collected vegetation samples for research, and worked on projects independently as well as with a team.

> -   Managed and led the restoration of a portion of a UCSB-owned wetland.

**Global Student Embassy, Santa Barbara, CA Trip Leader/Campus Representative (9/16--5/17)**

> -   Coordinated and led a group of peers to be a part of international reforestation and sustainable agriculture projects.

> -   Organized fundraising events, raising over \$15,000, to assist locals in Ecuador and Nicaragua.

### Skills, Certifications, and Affiliations

-   **Languages/Software:** R, Python, SQL, Git/GitHub, QGIS, ArcGIS, Tableau

-   **Environments:** Posit (RStudio), Visual Studio Code, JupyterLab

-   **Degree/Certifications:** Associate of Arts in Liberal Arts & Sciences: Mathematics and Science (May 2015), OSHA 40-Hour HAZWOPER, OSHA 10-Hour Construction Outreach

-   **Additional Experience:** Raised over $15,000 as a Campus Rep. (9/16-5/17) to aid Ecuador and Nicaragua locals

-   **Affiliations:** California Association of Environmental Professionals (AEP)
:::
